[package]
name = "aoc"
version = "0.1.0"
authors = ["Nick Saika <nicksaika@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
