[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Nick Saika <nicksaika@gmail.com>"]
edition = "2018"

[dependencies]
scan_fmt = "0.2.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
